# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BwL78o942LuaF8vfDaO39EfJCIMeNiU
"""

print("welcome to calaculator")
print("for addition you have enter 1")
print("for subtracion you have enter 2")
print("for multiplication you have enter 3")
print("for division you have enter 4")
print("enter a number")
a = int(input())
if (a==1):
  print("welcome to additon world of calculator")
  print("enter value of b")
  b=int(input())
  print("enter value of c")
  c=int(input())
  print(b+c)
elif a==2:
   print("welcome to subtraction world of calculator")
   print("enter value of b")
   b=int(input())
   print("enter value of c")
   c=int(input())
   print(b-c)
elif a==3:
   print("welcome to multiplication world of calculator")
   print("enter value of b")
   b=int(input())
   print("enter value of c")
   c=int(input())
   print(b*c) 
elif a==4:
   print("welcome to division world of calculator")
   print("enter value of b")
   b=int(input())
   print("enter value of c")
   c=int(input())
   print(b/c)